### ISSUE TITLE
CADBase Library does not display Readme.md in the FreeCAD Addon manager

### ISSUE THREAD

**Issue by GyleIverson** [mnnxp/cadbaselibrary-freecad#1]
CADBase Library does not display README.md in the FreeCAD Addon manager. The link is incorrect.

![Image 12-3-24 at 14 46](https://github.com/user-attachments/assets/32788a5e-517b-4a87-b248-ee9f8b15fe78)

**Comment by mnnxp** [comment]
Hello! Thank you for creating this issue. I'll get right on it.

**Comment by mnnxp** [comment]
Done.

https://github.com/mnnxp/cadbaselibrary-freecad/commit/0ea3fec451372237f5fa5d1359bc17681f00decc#diff-37a67ff78eb7260214b323353263b9af40a2fa98719a1e81937fae0159df87a3R12

Thank you again. I would be happy to answer your questions about the workbench if you have any.
